# Generated by Django 4.2.7 on 2023-12-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=300)),
                ('Category', models.CharField(max_length=300)),
                ('Precio', models.IntegerField(default=0)),
                ('rebaja', models.IntegerField(default=0)),
                ('new', models.BooleanField(default=False)),
                ('Timage', models.IntegerField(default=0)),
            ],
        ),
    ]
