# Generated by Django 4.2.7 on 2023-12-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Timage',
            field=models.ImageField(null=True, upload_to='Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='new',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rebaja',
            field=models.IntegerField(),
        ),
    ]
