# Generated by Django 4.2.7 on 2023-12-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='Cate',
        ),
    ]
